name: second_workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: run hello world
        run: |
              echo "Hello World"
              echo "Bye World"
